name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.2
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: cmake
      run: cd /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative; cmake .
    - name: make
      run: cd /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative; make
    - name: mkdir build
      run: |
        mkdir /home/runner/work/build
        cp /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative/PhysXSharpNative/libPhysXSharpNative.so /home/runner/work/build
        cp -r /home/runner/work/PhysXSharp/PhysXSharp/Prebuilt/physx3.4_linux64/release/bin/* /home/runner/work/build
        ls /home/runner/work/build
            mkdir /home/runner/work/build-zip
    - name: Easy Zip Files
      uses: papeloto/action-zip@v1
      with:
        # Files or directories to zip
        files: /home/runner/work/build
        # Name of output zip file
        dest: /home/runner/work/build-zip/build.zip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build-zip
