name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.2
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: cmake
      run: cd PhysXSharpNative; cmake .
    - name: make
      run: cd PhysXSharpNative; make
    - name: mkdir build
      run: |
        mkdir build
        mkdir build-zip
        cp PhysXSharpNative/PhysXSharpNative/libPhysXSharpNative.so build
        cp -r Prebuilt/physx3.4_linux64/release/bin/* build
    - name: Easy Zip Files
      uses: papeloto/action-zip@v1
      with:
        # Files or directories to zip
        files: build/
        # Name of output zip file
        dest: build.zip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ${{ github.workspace }}/build.zip
