name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.2
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: cmake
      run: cd /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative; cmake .
    - name: make
      run: cd /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative; make
    - name: mkdir build
      run: mkdir /home/runner/work/build
    - name: copy
      run: cp /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative/PhysXSharpNative/libPhysXSharpNative.so /home/runner/work/build
    - name: copy 2
      run: cp -r /home/runner/work/PhysXSharp/PhysXSharp/Prebuilt/**/*.so /home/runner/work/build
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: /home/runner/work/build/build.zip
        # Base path for archive files
        path: /home/runner/work/build
        # Working directory before zipping
        directory: /home/runner/work/build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/build/build.zip
