name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.2
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule sync
        git submodule update --init --recursive
    - name: cmake
      run: cd /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative; cmake .
    - name: make
      run: cd /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative; make
    - name: mkdir build
      run: |
        mkdir /home/runner/work/build
        cp /home/runner/work/PhysXSharp/PhysXSharp/PhysXSharpNative/PhysXSharpNative/libPhysXSharpNative.so /home/runner/work/build
        cp -r /home/runner/work/PhysXSharp/PhysXSharp/Prebuilt/physx3.4_linux64/release/bin/* /home/runner/work/build
    - uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r /home/runner/work/build.zip /home/runner/work/build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/build.zip
